# Generated by Django 5.1.1 on 2024-10-03 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории (например, "Еда", "Транспорт").', max_length=100, verbose_name='Название категории')),
                ('user', models.ForeignKey(help_text='Выберите пользователя, которому принадлежит данная категория.', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Введите сумму расхода (например, 500.00).', max_digits=10, verbose_name='Сумма расхода')),
                ('date', models.DateField(help_text='Выберите дату совершения расхода.', verbose_name='Дата расхода')),
                ('description', models.TextField(blank=True, help_text='Введите описание расхода (необязательное поле).', null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='Выберите категорию, к которой относится этот расход.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main.category', verbose_name='Категория')),
                ('user', models.ForeignKey(help_text='Выберите пользователя, которому принадлежит данный расход.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Введите сумму дохода (например, 1500.00).', max_digits=10, verbose_name='Сумма дохода')),
                ('date', models.DateField(help_text='Выберите дату получения дохода.', verbose_name='Дата дохода')),
                ('description', models.TextField(blank=True, help_text='Введите описание дохода (необязательное поле).', null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='Выберите категорию, к которой относится этот доход.', on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='main.category', verbose_name='Категория')),
                ('user', models.ForeignKey(help_text='Выберите пользователя, которому принадлежит данный доход.', on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
                'ordering': ['-date'],
            },
        ),
    ]
